;METADATA=(Diff=true, UseCommands=true)
[/Script/GameplayTags.GameplayTagsSettings]
ImportTagsFromConfig=True
WarnOnInvalidTags=True
ClearInvalidTags=False
AllowEditorTagUnloading=True
AllowGameTagUnloading=False
FastReplication=False
bDynamicReplication=False
InvalidTagCharacters="\"\',"
NumBitsForContainerSize=6
NetIndexFirstBitSegment=16
+GameplayTagList=(Tag="Event.Sauce.Catch",DevComment="Sent to a player actor when a thrown BP_SauceMaster overlaps them; triggers GA_Catch")
+GameplayTagList=(Tag="Player GrabbedObject",DevComment="")
+GameplayTagList=(Tag="State.Sauce.InFlight",DevComment="Applied to a BP_SauceMaster while it is airborne after being thrown by GA_Throw")

